# Generated by Django on 2025-05-23 12:00

from django.db import migrations, models
from django.conf import settings
from django.contrib.postgres.indexes import BrinIndex

IS_SQLITE = settings.DJANGO_DB == settings.DJANGO_DB_SQLITE

if IS_SQLITE:
    from django.db.migrations import AddIndex
else:
    from django.contrib.postgres.operations import AddIndexConcurrently as AddIndex


class Migration(migrations.Migration):

    atomic = IS_SQLITE

    dependencies = [
        ("tasks", "0053_annotation_bulk_created"),
    ]

    # use brin index for updated_at column because we need to keep good performance, 
    # brin is faster than btree for large tables
    operations = [
        AddIndex(
            model_name="task",
            index=BrinIndex(fields=["updated_at"], name="task_updated_at_brin_idx"),
        ),
    ] 