export { ReactComponent as IconExternal } from "./external.svg";
export { ReactComponent as IconFolderAdd } from "./folder-add.svg";
export { ReactComponent as IconHome } from "./home.svg";
export { ReactComponent as IconUserAdd } from "./user-add.svg";
export { ReactComponent as IconHumanSignal } from "./humansignal.svg";
export { ReactComponent as IconUpload } from "./upload.svg";
export { ReactComponent as IconLaunch } from "./launch.svg";
export { ReactComponent as IconFileCopy } from "./file-copy.svg";
export { ReactComponent as IconUndo } from "./undo.svg";
export { ReactComponent as IconRedo } from "./redo.svg";
export { ReactComponent as IconRemove } from "./remove.svg";
export { ReactComponent as IconPlus } from "./plus.svg";
export { ReactComponent as IconSparks } from "./sparks.svg";
export { ReactComponent as IconComment } from "./comment-check.svg";
export { ReactComponent as IconCommentRed } from "./comment-red.svg";
export { ReactComponent as IconCommentResolved } from "./comment-resolved.svg";
export { ReactComponent as IconCommentUnresolved } from "./comment-unresolved.svg";
export { ReactComponent as IconAnnotation } from "./annotation.svg";
export { ReactComponent as IconGrid } from "./grid.svg";
export { ReactComponent as IconSettings } from "./settings.svg";
export { ReactComponent as IconStar } from "./star.svg";
export { ReactComponent as IconStarOutline } from "./star-outline.svg";
export { ReactComponent as IconBan } from "./ban.svg";
export { ReactComponent as IconVisible } from "./visible.svg";
export { ReactComponent as IconInvisible } from "./invisible.svg";
export { ReactComponent as IconChevron } from "./chevron.svg";
export { ReactComponent as IconExpand } from "./expand.svg";
export { ReactComponent as IconExpandSmall } from "./expand-small.svg";
export { ReactComponent as IconCollapse } from "./collapse.svg";
export { ReactComponent as IconCollapseSmall } from "./collapse-small.svg";
export { ReactComponent as IconDate } from "./date.svg";
export { ReactComponent as IconClose } from "./close.svg";
export { ReactComponent as IconCloseCircleOutline } from "./close-circle-outline.svg";
export { ReactComponent as IconPlusCircle } from "./plus-circle.svg";
export { ReactComponent as IconSlow } from "./slow.svg";
export { ReactComponent as IconFast } from "./fast.svg";
export { ReactComponent as IconFileUpload } from "./file-upload.svg";
export { ReactComponent as IconDuplicate } from "./duplicate.svg";
export { ReactComponent as IconEllipsis } from "./ellipsis.svg";
export { ReactComponent as IconEllipsisVertical } from "./ellipsis-vertical.svg";
export { ReactComponent as IconWarning } from "./warning.svg";
export { ReactComponent as IconPlay } from "./play.svg";
export { ReactComponent as IconPause } from "./pause.svg";
export { ReactComponent as IconHelp } from "./help.svg";

export { ReactComponent as IconCheck } from "./check.svg";
export { ReactComponent as IconCheckBold } from "./check-bold.svg";
export { ReactComponent as IconCheckCircleOutline } from "./check-circle-outline.svg";
export { ReactComponent as IconCross } from "./cross.svg";
export { ReactComponent as IconCrossBold } from "./cross-bold.svg";

export { ReactComponent as IconVolumeMute } from "./volume-mute.svg";
export { ReactComponent as IconVolumeHalf } from "./volume-half.svg";
export { ReactComponent as IconVolumeFull } from "./volume-full.svg";

// Tools
export { ReactComponent as IconBrushTool } from "./tools/brush-tool.svg";
export { ReactComponent as IconBrushToolSmart } from "./tools/brush-tool-smart.svg";
export { ReactComponent as IconCircleTool } from "./tools/circle-tool.svg";
export { ReactComponent as IconCircleToolSmart } from "./tools/circle-tool-smart.svg";
export { ReactComponent as IconKeypointsTool } from "./tools/keypoints-tool.svg";
export { ReactComponent as IconKeypointsToolSmart } from "./tools/keypoints-tool-smart.svg";
export { ReactComponent as IconPolygonTool } from "./tools/polygon-tool.svg";
export { ReactComponent as IconPolygonToolSmart } from "./tools/polygon-tool-smart.svg";
export { ReactComponent as IconRectangleTool } from "./tools/rectangle-tool.svg";
export { ReactComponent as IconRectangleToolSmart } from "./tools/rectangle-tool-smart.svg";
export { ReactComponent as IconRectangle3PointTool } from "./tools/rectangle-3point-tool.svg";
export { ReactComponent as IconRectangle3PointToolSmart } from "./tools/rectangle-3point-tool-smart.svg";
export { ReactComponent as IconMagicWandTool } from "./tools/magic-wand-tool.svg";
export { ReactComponent as IconEraserTool } from "./tools/eraser-tool.svg";
export { ReactComponent as IconHandTool } from "./tools/hand-tool.svg";
export { ReactComponent as IconBrightnessTool } from "./tools/brightness-tool.svg";
export { ReactComponent as IconContrastTool } from "./tools/contrast-tool.svg";

export { ReactComponent as IconZoomIn } from "./tools/magnify-tool.svg";
export { ReactComponent as IconZoomOut } from "./tools/minify-tool.svg";
export { ReactComponent as IconExpandTool } from "./tools/expand-tool.svg";
export { ReactComponent as IconMoveTool } from "./tools/move-tool.svg";
export { ReactComponent as IconRotate } from "./rotate.svg";
export { ReactComponent as IconRotateLeftTool } from "./tools/rotate-left-tool.svg";
export { ReactComponent as IconRotateRightTool } from "./tools/rotate-right-tool.svg";
export { ReactComponent as IconInfoOutline } from "./info-outline.svg";
export { ReactComponent as IconInfo } from "./info.svg";
export { ReactComponent as IconCopy } from "./copy.svg";
export { ReactComponent as IconText } from "./text.svg";
export { ReactComponent as IconViewAll } from "./view-all.svg";
export { ReactComponent as IconLink } from "./link.svg";
export { ReactComponent as IconRelationLink } from "./link-relation.svg";
export { ReactComponent as IconTrash } from "./trash.svg";
export { ReactComponent as IconTrashAlt } from "./trash-alt.svg";
export { ReactComponent as IconTrashRect } from "./trash-rect.svg";
export { ReactComponent as IconMenu } from "./menu.svg";
export { ReactComponent as IconMinus } from "./minus.svg";
export { ReactComponent as IconHamburger } from "./hamburger.svg";
export { ReactComponent as IconDetails } from "./details.svg";
export { ReactComponent as IconLockLocked } from "./locked.svg";
export { ReactComponent as IconLockUnlocked } from "./unlocked.svg";
export { ReactComponent as IconCursor } from "./cursor.svg";
export { ReactComponent as IconList } from "./list.svg";
export { ReactComponent as IconSend } from "./send.svg";
export { ReactComponent as IconSpeed } from "./speed.svg";
export { ReactComponent as IconSortUp } from "./sort-up.svg";
export { ReactComponent as IconSortDown } from "./sort-down.svg";
export { ReactComponent as IconFilter } from "./filter.svg";
export { ReactComponent as IconDelete } from "./delete.svg";
export { ReactComponent as IconModels } from "./models.svg";
export { ReactComponent as IconEdit } from "./edit.svg";

export { ReactComponent as IconArrowLeft } from "./arrow-left.svg";
export { ReactComponent as IconArrowRight } from "./arrow-right.svg";

// Relations
export { ReactComponent as IconRelationRight } from "./relations/right.svg";
export { ReactComponent as IconRelationLeft } from "./relations/left.svg";
export { ReactComponent as IconRelationBi } from "./relations/bi.svg";

// Properties
export { ReactComponent as IconPropertyAngle } from "./properties/angle.svg";

export { ReactComponent as IconBanSquare } from "./ban.svg";
export { ReactComponent as IconCheckAlt } from "./check_alt.svg";
export { ReactComponent as IconCrossAlt } from "./cross_alt.svg";
export { ReactComponent as IconSparkSquare } from "./spark-square.svg";
export { ReactComponent as IconThumbsDown } from "./thumbs-down.svg";
export { ReactComponent as IconThumbsUp } from "./thumbs-up.svg";
export { ReactComponent as IconStarSquare } from "./star_square.svg";
export { ReactComponent as IconGear } from "./gear.svg";
export { ReactComponent as IconGearNewUI } from "./gear_new_menu.svg";
export { ReactComponent as IconCommentCheck } from "./comment_check.svg";

export { ReactComponent as IconBell } from "./bell.svg";
export { ReactComponent as IconBook } from "./book.svg";
export { ReactComponent as IconBulb } from "./bulb.svg";
export { ReactComponent as IconChevronLeft } from "./chevron-left.svg";
export { ReactComponent as IconChevronRight } from "./chevron-right.svg";
export { ReactComponent as IconChevronDown } from "./chevron-down.svg";
export { ReactComponent as IconDoor } from "./door.svg";
export { ReactComponent as IconError } from "./error.svg";
export { ReactComponent as IconFolder } from "./folder.svg";
export { ReactComponent as IconFolderOpen } from "./folder-open.svg";
export { ReactComponent as IconPersonInCircle } from "./person-circle.svg";
export { ReactComponent as IconPin } from "./pin.svg";
export { ReactComponent as IconSlack } from "./slack.svg";
export { ReactComponent as IconTerminal } from "./terminal.svg";
export { ReactComponent as IconPencil } from "./pencil.svg";
export { ReactComponent as IconPredictions } from "./predictions.svg";
export { ReactComponent as IconSpark } from "./spark.svg";

export { ReactComponent as IconBoundingBox } from "./bounding-box.svg";
export { ReactComponent as IconClockTimeFourOutline } from "./clock-time-four-outline.svg";
export { ReactComponent as IconQuestionOutline } from "./question-outline.svg";
export { ReactComponent as IconCode } from "./code.svg";

export * from "./annotation";
export * from "./outliner";
export * from "./comment";
export * from "./timeline";
export * from "./tree";

export { ReactComponent as IconArrowRightBlue } from "./arrow-right-blue.svg";
export { ReactComponent as IconArrowRightBottom } from "./arrow-right-bottom.svg";
export { ReactComponent as IconBouncing3Dots } from "./bouncing-3-dots.svg";
export { ReactComponent as IconBubbleSpike } from "./bubble-spike.svg";
export { ReactComponent as IconBubbleSpikeAlt } from "./bubble-spike-alt.svg";
export { ReactComponent as IconBulkLabeling } from "./bulk-labeling.svg";
export { ReactComponent as IconCalendar } from "./calendar.svg";
export { ReactComponent as IconCheckCircle } from "./check-circle.svg";
export { ReactComponent as IconCheckCircleFilled } from "./check-circle-filled.svg";
export { ReactComponent as IconCheckCircleGreen } from "./check-circle-green.svg";
export { ReactComponent as IconCheckCircleFilledGreen } from "./check-circle-filled-green.svg";
export { ReactComponent as IconCheckCircleBlue } from "./check-circle-blue.svg";
export { ReactComponent as IconCheck2 } from "./check2.svg";
export { ReactComponent as IconCheck3 } from "./check3.svg";
export { ReactComponent as IconChevronLeftSmall } from "./chevron-left-small.svg";
export { ReactComponent as IconChevronLeftBold } from "./chevron-left-bold.svg";
export { ReactComponent as IconCopyOutline } from "./copy-outline.svg";
export { ReactComponent as IconChevronRightBold } from "./chevron-right-bold.svg";
export { ReactComponent as IconChevronRightSmall } from "./chevron-right-small.svg";
export { ReactComponent as IconClock } from "./clock.svg";
export { ReactComponent as IconCollapseToSidebar } from "./collapse-to-sidebar.svg";
export { ReactComponent as IconCrossNoPadding } from "./cross-no-padding.svg";
export { ReactComponent as IconCrossCircleFilledRed } from "./cross-circle-filled-red.svg";
export { ReactComponent as IconDatasets } from "./datasets.svg";
export { ReactComponent as IconDocument } from "./document.svg";
export { ReactComponent as IconDown } from "./down.svg";
export { ReactComponent as IconDragIndicator } from "./drag-indicator.svg";
export { ReactComponent as IconErrorAlt } from "./error-alt.svg";
export { ReactComponent as IconExpandDiagonal } from "./expand-diagonal.svg";
export { ReactComponent as IconFolderPlus } from "./folder-plus-outline.svg";
export { ReactComponent as IconFolderSpark } from "./folder-spark-outline.svg";
export { ReactComponent as IconGitHub } from "./github.svg";
export { ReactComponent as IconHistoryRewind } from "./history-rewind.svg";
export { ReactComponent as IconInfoFilled } from "./info-filled.svg";
export { ReactComponent as IconIO } from "./io.svg";
export { ReactComponent as IconMastercard } from "./mastercard.svg";
export { ReactComponent as IconReload } from "./reload.svg";
export { ReactComponent as IconRefresh } from "./refresh.svg";
export { ReactComponent as IconThumbsDownFill } from "./thumbs-down-fill.svg";
export { ReactComponent as IconThumbsDownOutline } from "./thumbs-down-outline.svg";
export { ReactComponent as IconThumbsUpFill } from "./thumbs-up-fill.svg";
export { ReactComponent as IconThumbsUpOutline } from "./thumbs-up-outline.svg";
export { ReactComponent as IconVisa } from "./visa.svg";
export { ReactComponent as IconWarningCircle } from "./warning-circle.svg";
export { ReactComponent as IconWarningCircleFilled } from "./warning-circle-filled.svg";
export { ReactComponent as IconSearch } from "./search.svg";
export { ReactComponent as CopyIcon } from "./content-copy.svg";
export { ReactComponent as FileDownload } from "./file-download.svg";
export { ReactComponent as FileDownloadBlack } from "./file_download_black.svg";
export { ReactComponent as IconSoundBars } from "./sound-bars.svg";
export { ReactComponent as IconSparks3 } from "./sparks-3.svg";
export { ReactComponent as IconSparksStop } from "./sparks-stop.svg";
export { ReactComponent as IconUploadOutline } from "./cloud-upload-outline.svg";
export { ReactComponent as IconBlueCheckmark } from "./blue-checkmark.svg";
export { ReactComponent as IconModelVersion } from "./model-version.svg";
export { ReactComponent as IconStarRectangle } from "./star_rectangle.svg";
export { ReactComponent as IconBanner } from "./banner-icon.svg";
export { ReactComponent as IconEmptyFolder } from "./folder-empty.svg";
export { ReactComponent as IconLsLabeling } from "./ls-labeling.svg";
export { ReactComponent as IconLsReview } from "./ls-review.svg";
export { ReactComponent as IconModel } from "./model.svg";
export { ReactComponent as IconAllProjects } from "./all-projects.svg";
export { ReactComponent as IconSync } from "./sync.svg";
export { ReactComponent as IconSyncDisabled } from "./sync-disabled.svg";

// full-color icons
export { ReactComponent as IconPlaylistStarFullcolor } from "./full_color_playlist_star.svg";
