// This file will be generated by the design-tokens-converter tool
// Run 'nx design-tokens ui' to populate this file with tokens from designvariables.json

const designTokens = {
  colors: {
    // Colors will be generated here
  },
};

module.exports = designTokens;
