// This file will be generated by the design-tokens-converter.js script
// Run the script to populate this file with tokens from design-tokens.json

const designTokens = {
  colors: {
    // Colors will be generated here
  },
};

module.exports = designTokens;
