# Generated by Django 3.2.16 on 2025-06-15 08:22

from django.db import migrations, models
from ..uploader import full_files_hash

def migration_full_files_hash(apps, schema_editor):
    full_files_hash()

class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0002_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="file_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.RunPython(migration_full_files_hash),
    ]
