steps:
  - target: .lsf-auto-labeling-button
    placement: bottom
    title: 'Great news!'
    content: 'You can now rapidly label this project using Label Studio Prompts with the power of LLMs.<br/><br/>Click “Auto-Label Tasks” to automatically label a sample of 20 tasks.'
    disableBeacon: true
