# Generated by Django 5.1.10 on 2025-07-15 18:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organizationmember_deleted_at'),
        ('projects', '0028_auto_20241107_1031'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def apply_postgres_operations(apps, schema_editor):
        if schema_editor.connection.vendor == 'postgresql':
            Project = apps.get_model('projects', 'Project')
            # Create the search vector field
            schema_editor.execute(
                'ALTER TABLE project ADD COLUMN IF NOT EXISTS search_vector tsvector '
                'GENERATED ALWAYS AS ('
                'setweight(to_tsvector(\'english\', COALESCE(id::text, \'\')), \'A\') || '
                'setweight(to_tsvector(\'english\', COALESCE(title, \'\')), \'B\') || '
                'setweight(to_tsvector(\'english\', COALESCE(description, \'\')), \'C\')'
                ') STORED;'
            )
            # Create the GIN index
            schema_editor.execute(
                'CREATE INDEX IF NOT EXISTS project_search_vector_idx ON project USING GIN (search_vector);'
            )

    def revert_postgres_operations(apps, schema_editor):
        if schema_editor.connection.vendor == 'postgresql':
            # Drop the index first
            schema_editor.execute('DROP INDEX IF EXISTS project_search_vector_idx;')
            # Drop the column
            schema_editor.execute('ALTER TABLE project DROP COLUMN IF EXISTS search_vector;')

    operations = [
        migrations.RunPython(
            apply_postgres_operations,
            revert_postgres_operations,
        ),
    ]
