# Generated by Django 5.1.10 on 2025-07-16 19:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models
from django.db import connection

class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
        ("projects", "0028_auto_20241107_1031"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    if connection.vendor == 'postgresql':
        operations = [
            migrations.AddField(
                model_name="project",
                name="search_vector",
                field=models.GeneratedField(
                    db_persist=True,
                    expression=django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.SearchVector("id", weight="A"),
                            "||",
                            django.contrib.postgres.search.SearchVector(
                                "title", weight="B"
                            ),
                            None,
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "description", weight="C"
                        ),
                        None,
                    ),
                    output_field=django.contrib.postgres.search.SearchVectorField(),
                ),
            ),
            migrations.AddIndex(
                model_name="project",
                index=django.contrib.postgres.indexes.GinIndex(
                    fields=["search_vector"], name="project_search_vector_idx"
                ),
            ),
        ]
    else:
        operations = [
            migrations.AddField(
                model_name='project',
                name='search_vector',
                field=models.TextField(blank=True, null=True),
            ),
        ]