# Generated by Django 4.2.15 on 2024-12-17 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20231201_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for the product tour. Name must match the config name.', max_length=256)),
                ('state', models.CharField(choices=[('ready', 'ready'), ('completed', 'completed'), ('skipped', 'skipped')], default='ready', help_text='Current state of the tour for this user: "ready" when tour is initiated, "completed" when user finishes the tour, "skipped" when user cancels the tour.', max_length=32)),
                ('interaction_data', models.JSONField(blank=True, default=dict, help_text='Additional data about user interaction with the tour')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this tour record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this tour record was last updated')),
                ('user', models.ForeignKey(help_text='User who interacted with the tour', on_delete=django.db.models.deletion.CASCADE, related_name='tours', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
