# Generated by Django 5.1.10 on 2025-08-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_custom_hotkeys"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
