# Generated by Django 5.1.9 on 2025-06-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("io_storages", "0019_azureblobimportstoragelink_row_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="s3importstorage",
            name="recursive_scan",
            field=models.BooleanField(
                default=False,
                help_text="Include files from all nested folders",
                verbose_name="recursive scan",
            ),
        ),
    ]
